{
 "title": "Nmap Dashboard",
 "description": "View and analyze Nmap results with this Grafana Dashboard. ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Hosts Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT unix_timestamp as time, \n       value as value1, \n       value * 2 as value2\nFROM raw_table\nWHERE time >= 1739064348376 / 1000 AND time < 1741656348376 / 1000\nORDER BY time DESC\nLIMIT 1\n\n-- SELECT unix_timestamp as time, value as value1, value*2 as value2 From raw_table\n-- WHERE time >= 1739064348376 / 1000 and time < 1741656348376 / 1000\n\n-- SELECT COUNT(DISTINCT ip) AS count\n-- FROM hosts\n-- WHERE start_time >= 1739064348376 AND end_time <= 1741656348376;\n",
     "rawQueryText": "SELECT unix_timestamp as time, \n       value as value1, \n       value * 2 as value2\nFROM raw_table\nWHERE time >= $__from / 1000 AND time < $__to / 1000\nORDER BY time DESC\nLIMIT 1\n\n-- SELECT unix_timestamp as time, value as value1, value*2 as value2 From raw_table\n-- WHERE time >= $__from / 1000 and time < $__to / 1000\n\n-- SELECT COUNT(DISTINCT ip) AS count\n-- FROM hosts\n-- WHERE start_time >= $__from AND end_time <= $__to;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Operating Systems",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "-- SELECT\n--   \"dddd5\" As \"os1\",\n--   66 AS \"count4\",6 AS \"count13\"\n-- From raw_table\n\n--  strftime('%H:%M', datetime(unix_timestamp, 'unixepoch')) AS time_group,\nSELECT \n    strftime('%H', datetime(unix_timestamp+ 32400, 'unixepoch')) AS time_group,\n    AVG(value) AS value\n    -- COUNT(value) AS \"count\"\n    \nFROM raw_table\nGROUP BY  strftime('%H', datetime(unix_timestamp+ 32400, 'unixepoch'))\n\n\n\n-- SELECT\n--   os,\n--   COUNT(*) AS \"count\"\n-- FROM hosts\n-- WHERE start_time >= $__from AND end_time < $__to\n-- GROUP BY os\n-- ORDER BY count DESC;\n\n    \n",
     "rawQueryText": "-- SELECT\n--   \"dddd5\" As \"os1\",\n--   66 AS \"count4\",6 AS \"count13\"\n-- From raw_table\n\n--  strftime('%H:%M', datetime(unix_timestamp, 'unixepoch')) AS time_group,\nSELECT \n    strftime('%H', datetime(unix_timestamp+ 32400, 'unixepoch')) AS time_group,\n    AVG(value) AS value\n    -- COUNT(value) AS \"count\"\n    \nFROM raw_table\nGROUP BY  strftime('%H', datetime(unix_timestamp+ 32400, 'unixepoch'))\n\n\n\n-- SELECT\n--   os,\n--   COUNT(*) AS \"count\"\n-- FROM hosts\n-- WHERE start_time >= $__from AND end_time < $__to\n-- GROUP BY os\n-- ORDER BY count DESC;\n\n    \n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Unidentified Services (open port)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    strftime('%H:%M', datetime(unix_timestamp+ 32400, 'unixepoch')) AS time_group,\n    AVG(value) AS value,\n    COUNT(value) AS \"count\"\n    \nFROM raw_table\nGROUP BY  strftime('%H:%M', datetime(unix_timestamp+ 32400, 'unixepoch'))\n\n-- SELECT p.port, COUNT(*) AS count\n-- FROM ports p\n-- JOIN hosts h ON p.host_id = h.id\n-- WHERE h.start_time >= $__from AND h.end_time < $__to\n--  AND p.service_info = '' AND p.state = 'open'\n-- GROUP BY p.port",
     "rawQueryText": "SELECT \n    strftime('%H:%M', datetime(unix_timestamp+ 32400, 'unixepoch')) AS time_group,\n    AVG(value) AS value,\n    COUNT(value) AS \"count\"\n    \nFROM raw_table\nGROUP BY  strftime('%H:%M', datetime(unix_timestamp+ 32400, 'unixepoch'))\n\n-- SELECT p.port, COUNT(*) AS count\n-- FROM ports p\n-- JOIN hosts h ON p.host_id = h.id\n-- WHERE h.start_time >= $__from AND h.end_time < $__to\n--  AND p.service_info = '' AND p.state = 'open'\n-- GROUP BY p.port",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Identified Services",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT unix_timestamp as time, value as value1, value*2 as value2 From raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 10;\n\n-- SELECT unix_timestamp as time, value as value1, value*2 as value2 From raw_table\n-- WHERE time >= $__from / 1000 and time < $__to / 1000\n\n-- SELECT p.service_info, COUNT(*) AS count\n-- FROM ports p\n-- JOIN hosts h ON p.host_id = h.id\n-- WHERE h.start_time >= $__from AND h.end_time < $__to\n-- AND p.service_info IS NOT NULL AND p.service_info <> ''\n-- GROUP BY p.service_info\n",
     "rawQueryText": "SELECT unix_timestamp as time, value as value1, value*2 as value2 From raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 10;\n\n-- SELECT unix_timestamp as time, value as value1, value*2 as value2 From raw_table\n-- WHERE time >= $__from / 1000 and time < $__to / 1000\n\n-- SELECT p.service_info, COUNT(*) AS count\n-- FROM ports p\n-- JOIN hosts h ON p.host_id = h.id\n-- WHERE h.start_time >= $__from AND h.end_time < $__to\n-- AND p.service_info IS NOT NULL AND p.service_info <> ''\n-- GROUP BY p.service_info\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Open Ports",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT unix_timestamp as time\n,value*(ABS(RANDOM() % 110)) / 10.0 as value3\nFrom raw_table\nLIMIT 1;\n\n-- SELECT SUM(unique_open_ports) AS total_unique_open_ports\n-- FROM (\n--   SELECT\n--     COUNT(DISTINCT p.port) AS unique_open_ports,\n--     h.ip AS host_ip\n--   FROM ports p\n--   JOIN hosts h ON p.host_id = h.id\n--   WHERE p.state = 'open' AND h.start_time >= 1739151884490 AND h.end_time < 1741743884490\n--   GROUP BY h.ip, p.port\n-- ) AS subquery;\n    ",
     "rawQueryText": "SELECT unix_timestamp as time\n,value*(ABS(RANDOM() % 110)) / 10.0 as value3\nFrom raw_table\nLIMIT 1;\n\n-- SELECT SUM(unique_open_ports) AS total_unique_open_ports\n-- FROM (\n--   SELECT\n--     COUNT(DISTINCT p.port) AS unique_open_ports,\n--     h.ip AS host_ip\n--   FROM ports p\n--   JOIN hosts h ON p.host_id = h.id\n--   WHERE p.state = 'open' AND h.start_time >= $__from AND h.end_time < $__to\n--   GROUP BY h.ip, p.port\n-- ) AS subquery;\n    ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Unique Ports",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT unix_timestamp as time\n,value*(ABS(RANDOM() % 110)) / 10.0 as value4\nFrom raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 1;\n",
     "rawQueryText": "SELECT unix_timestamp as time\n,value*(ABS(RANDOM() % 110)) / 10.0 as value4\nFrom raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 1;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Open Ports Found",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT \n    strftime('%H:%M', datetime(unix_timestamp+ 32400, 'unixepoch')) AS time_group,\n    AVG(value) AS value,\n    COUNT(value) AS \"count\"\n    \nFROM raw_table\nGROUP BY  strftime('%H:%M', datetime(unix_timestamp+ 32400, 'unixepoch'))\nORDER BY unix_timestamp DESC\nLIMIT 10;\n-- SELECT\n--   p.port,\n--   COUNT(DISTINCT h.ip) AS host_count\n-- FROM\n--   hosts h\n--   JOIN ports p ON h.id = p.host_id\n-- WHERE\n--   p.state = 'open' AND h.start_time >= $__from AND h.end_time < $__to\n-- GROUP BY\n--   p.port;",
     "rawQueryText": "SELECT \n    strftime('%H:%M', datetime(unix_timestamp+ 32400, 'unixepoch')) AS time_group,\n    AVG(value) AS value,\n    COUNT(value) AS \"count\"\n    \nFROM raw_table\nGROUP BY  strftime('%H:%M', datetime(unix_timestamp+ 32400, 'unixepoch'))\nORDER BY unix_timestamp DESC\nLIMIT 10;\n-- SELECT\n--   p.port,\n--   COUNT(DISTINCT h.ip) AS host_count\n-- FROM\n--   hosts h\n--   JOIN ports p ON h.id = p.host_id\n-- WHERE\n--   p.state = 'open' AND h.start_time >= $__from AND h.end_time < $__to\n-- GROUP BY\n--   p.port;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Scans",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT unix_timestamp as time\n,value*(ABS(RANDOM() % 110)) / 10.0 as value5\nFrom raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 1;",
     "rawQueryText": "SELECT unix_timestamp as time\n,value*(ABS(RANDOM() % 110)) / 10.0 as value5\nFrom raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT unix_timestamp as time, value as value1, value*2 as value2\n,value*(ABS(RANDOM() % 110)) / 10.0 as value3\n,value*(ABS(RANDOM() % 110)) / 10.0 as value4\n,value*(ABS(RANDOM() % 110)) / 10.0 as value5\n,value*(ABS(RANDOM() % 110)) / 10.0 as value6\n,value*(ABS(RANDOM() % 110)) / 10.0 as value7 \nFrom raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \n-- LIMIT 10;",
     "rawQueryText": "SELECT unix_timestamp as time, value as value1, value*2 as value2\n,value*(ABS(RANDOM() % 110)) / 10.0 as value3\n,value*(ABS(RANDOM() % 110)) / 10.0 as value4\n,value*(ABS(RANDOM() % 110)) / 10.0 as value5\n,value*(ABS(RANDOM() % 110)) / 10.0 as value6\n,value*(ABS(RANDOM() % 110)) / 10.0 as value7 \nFrom raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \n-- LIMIT 10;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT unix_timestamp as time, value as value1, value*2 as value2\n,value*(ABS(RANDOM() % 110)) / 10.0 as value3\n,value*(ABS(RANDOM() % 110)) / 10.0 as value4\n,value*(ABS(RANDOM() % 110)) / 10.0 as value5\n,value*(ABS(RANDOM() % 110)) / 10.0 as value6\n,value*(ABS(RANDOM() % 110)) / 10.0 as value7 \nFrom raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 10;\n\n-- SELECT ip, hostname, ports_tested, ports_open, ports_closed, ports_filtered FROM hosts\n-- WHERE start_time >= $__from AND end_time < $__to",
     "rawQueryText": "SELECT unix_timestamp as time, value as value1, value*2 as value2\n,value*(ABS(RANDOM() % 110)) / 10.0 as value3\n,value*(ABS(RANDOM() % 110)) / 10.0 as value4\n,value*(ABS(RANDOM() % 110)) / 10.0 as value5\n,value*(ABS(RANDOM() % 110)) / 10.0 as value6\n,value*(ABS(RANDOM() % 110)) / 10.0 as value7 \nFrom raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 10;\n\n-- SELECT ip, hostname, ports_tested, ports_open, ports_closed, ports_filtered FROM hosts\n-- WHERE start_time >= $__from AND end_time < $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Live Hosts and Open Ports over Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT unix_timestamp as time, value as value1, value*2 as value2 From raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \n-- ORDER BY time DESC \n-- LIMIT 10;\n\n-- SELECT\n--   start_time AS \"time\",\n--   total_open_ports AS \"open_ports\",\n--   total_hosts\n-- FROM scans\n-- WHERE\n--   start_time >= $__from / 1000\n--   AND start_time + elapsed_time < $__to / 1000\n-- ORDER BY start_time",
     "rawQueryText": "SELECT unix_timestamp as time, value as value1, value*2 as value2 From raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \n-- ORDER BY time DESC \n-- LIMIT 10;\n\n-- SELECT\n--   start_time AS \"time\",\n--   total_open_ports AS \"open_ports\",\n--   total_hosts\n-- FROM scans\n-- WHERE\n--   start_time >= $__from / 1000\n--   AND start_time + elapsed_time < $__to / 1000\n-- ORDER BY start_time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Port Tested Per Second by Host",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT \n    strftime('%H:%M', datetime(unix_timestamp + 32400, 'unixepoch')) AS time_group,\n    AVG(value) AS value,\n    COUNT(value) AS \"count\"\n    \nFROM raw_table\nGROUP BY  strftime('%H:%M', datetime(unix_timestamp + 32400, 'unixepoch'))\n\n-- SELECT unix_timestamp as time, \n-- value*(ABS(RANDOM() % 110)) / 10.0 as value2\n-- From raw_table\n-- WHERE time >= $__from / 1000 and time < $__to / 1000 \n-- ORDER BY time DESC \n-- LIMIT 10;\n\n-- SELECT ip, \n--        (ports_tested * 1.0) / ((end_time - start_time) / 1000) AS avg_ports_per_second\n-- FROM hosts\n-- WHERE start_time >= $__from AND end_time < $__to AND ports_tested IS NOT NULL\n-- ORDER BY ip;",
     "rawQueryText": "SELECT \n    strftime('%H:%M', datetime(unix_timestamp + 32400, 'unixepoch')) AS time_group,\n    AVG(value) AS value,\n    COUNT(value) AS \"count\"\n    \nFROM raw_table\nGROUP BY  strftime('%H:%M', datetime(unix_timestamp + 32400, 'unixepoch'))\n\n-- SELECT unix_timestamp as time, \n-- value*(ABS(RANDOM() % 110)) / 10.0 as value2\n-- From raw_table\n-- WHERE time >= $__from / 1000 and time < $__to / 1000 \n-- ORDER BY time DESC \n-- LIMIT 10;\n\n-- SELECT ip, \n--        (ports_tested * 1.0) / ((end_time - start_time) / 1000) AS avg_ports_per_second\n-- FROM hosts\n-- WHERE start_time >= $__from AND end_time < $__to AND ports_tested IS NOT NULL\n-- ORDER BY ip;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT unix_timestamp as time, value as value1, value*2 as value2\n,value*(ABS(RANDOM() % 110)) / 10.0 as value3\n,value*(ABS(RANDOM() % 110)) / 10.0 as value4\n,value*(ABS(RANDOM() % 110)) / 10.0 as value5\n,value*(ABS(RANDOM() % 110)) / 10.0 as value6\n,value*(ABS(RANDOM() % 110)) / 10.0 as value7 \nFrom raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 10;",
     "rawQueryText": "SELECT unix_timestamp as time, value as value1, value*2 as value2\n,value*(ABS(RANDOM() % 110)) / 10.0 as value3\n,value*(ABS(RANDOM() % 110)) / 10.0 as value4\n,value*(ABS(RANDOM() % 110)) / 10.0 as value5\n,value*(ABS(RANDOM() % 110)) / 10.0 as value6\n,value*(ABS(RANDOM() % 110)) / 10.0 as value7 \nFrom raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 10;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Scans Loaded",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "queryText": "SELECT unix_timestamp as time\n,value as value1\n,value*2 as value2 \n,value*(ABS(RANDOM() % 110)) / 10.0 as value3\n,value*(ABS(RANDOM() % 110)) / 10.0 as value4\n,value*(ABS(RANDOM() % 110)) / 10.0 as value5\n,value*(ABS(RANDOM() % 110)) / 10.0 as value6\nFrom raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 10;\n\n-- SELECT\n--   datetime(start_time, 'unixepoch') AS start_time_utc,\n--   nmap_version,\n--   command_line,\n--   elapsed_time,\n--   total_hosts,\n--   total_open_ports\n-- FROM scans\n-- WHERE\n--   start_time >= $__from / 1000\n--   AND start_time + elapsed_time < $__to / 1000",
     "rawQueryText": "SELECT unix_timestamp as time\n,value as value1\n,value*2 as value2 \n,value*(ABS(RANDOM() % 110)) / 10.0 as value3\n,value*(ABS(RANDOM() % 110)) / 10.0 as value4\n,value*(ABS(RANDOM() % 110)) / 10.0 as value5\n,value*(ABS(RANDOM() % 110)) / 10.0 as value6\nFrom raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 10;\n\n-- SELECT\n--   datetime(start_time, 'unixepoch') AS start_time_utc,\n--   nmap_version,\n--   command_line,\n--   elapsed_time,\n--   total_hosts,\n--   total_open_ports\n-- FROM scans\n-- WHERE\n--   start_time >= $__from / 1000\n--   AND start_time + elapsed_time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Open Services",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "queryText": "SELECT unix_timestamp as time, value as value1, value*2 as value2 From raw_table\nWHERE time >= 1739423174159 / 1000 and time < 1739480369746 / 1000 \nORDER BY time DESC \nLIMIT 10;\n\n-- SELECT h.ip, p.protocol, p.port, p.service_info, p.http_title, p.ssl_common_name, p.ssl_issuer\n-- FROM ports p\n-- JOIN hosts h ON p.host_id = h.id\n-- WHERE h.start_time >= 1739423174159 AND h.end_time < 1739480369746\n-- AND p.state = 'open'\n",
     "rawQueryText": "SELECT unix_timestamp as time, value as value1, value*2 as value2 From raw_table\nWHERE time >= $__from / 1000 and time < $__to / 1000 \nORDER BY time DESC \nLIMIT 10;\n\n-- SELECT h.ip, p.protocol, p.port, p.service_info, p.http_title, p.ssl_common_name, p.ssl_issuer\n-- FROM ports p\n-- JOIN hosts h ON p.host_id = h.id\n-- WHERE h.start_time >= $__from AND h.end_time < $__to\n-- AND p.state = 'open'\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}